[tox]
isolated_build = true
envlist = ruff, ruff_lint, pytest, mypy
requires = tox-uv

[testenv]
passenv = *
runner = uv-venv-runner

[testenv:ruff]
description = 'Execute static analysis with ruff.'
skip_install = true
deps = ruff
commands = ruff format . --check

[testenv:ruff_lint]
description = 'Execute static analysis with Ruff.'
skip_install = true
deps = ruff
commands = ruff check .

[testenv:pytest]
description = 'Run tests with pytest.'
commands = pytest tests/

[testenv:mypy]
deps =
    mypy
    pytest
    pytz
    types-pytz
    six
    types-six
    bleach
    types-bleach
    freezegun
    sqlalchemy
commands =
    mypy cornflake tests