[tox]
isolated_build = true
envlist = ruff, ruff-lint, pytest, mypy, deptry
requires = tox-uv

[testenv]
passenv = *
runner = uv-venv-runner

[testenv:ruff]
description = 'Execute static analysis with ruff.'
skip_install = true
deps = ruff
commands = ruff format . --check

[testenv:ruff_lint]
description = 'Execute static analysis with Ruff.'
skip_install = true
deps = ruff
commands = ruff check .

[testenv:pytest]
description = 'Run tests with pytest.'
commands = pytest tests/
